#!/usr/bin/env python3
"""Write the 2026-08-18 open-data name held-out. Not a frozen fixture."""

import json
from pathlib import Path

ROWS = [
    {
        "id": "od-name-001",
        "readings": ["ㄨㄛˇ", "ㄓㄨˋ", "ㄗㄞˋ", "ㄋㄢˊ", "ㄍㄤˇ", "ㄑㄩ"],
        "expected": "我住在南港區",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "南港區 is in data.txt",
    },
    {
        "id": "od-name-002",
        "readings": ["ㄊㄚ", "ㄗㄞˋ", "ㄒㄧㄥˊ", "ㄓㄥˋ", "ㄩㄢˋ", "ㄕㄤˋ", "ㄅㄢ"],
        "expected": "他在行政院上班",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "行政院 is in data.txt",
    },
    {
        "id": "od-name-003",
        "readings": ["ㄐㄧㄢˋ", "ㄅㄠˇ", "ㄕㄨˇ", "ㄧㄡˇ", "ㄍㄨㄥ", "ㄍㄠˋ"],
        "expected": "健保署有公告",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "健保署 is in data.txt",
    },
    {
        "id": "od-name-004",
        "readings": ["ㄗㄨㄛˋ", "ㄅㄢˇ", "ㄋㄢˊ", "ㄒㄧㄢˋ", "ㄅㄧˇ", "ㄐㄧㄠˋ", "ㄎㄨㄞˋ"],
        "expected": "坐板南線比較快",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "板南線 is in data.txt",
    },
    {
        "id": "od-name-005",
        "readings": ["ㄊㄞˊ", "ㄓㄨㄥ", "ㄕˋ", "ㄐㄧㄣ", "ㄊㄧㄢ", "ㄏㄣˇ", "ㄖㄜˋ"],
        "expected": "台中市今天很熱",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present_variant",
        "notes": "data.txt has 台中市; official 臺中市 is absent as a whole phrase",
    },
    {
        "id": "od-name-006",
        "readings": ["ㄍㄠ", "ㄒㄩㄥˊ", "ㄕˋ", "ㄗㄞˋ", "ㄒㄧㄚˋ", "ㄩˇ"],
        "expected": "高雄市在下雨",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "高雄市 is in data.txt",
    },
    {
        "id": "od-name-007",
        "readings": ["ㄨㄟˋ", "ㄕㄥ", "ㄈㄨˊ", "ㄌㄧˋ", "ㄅㄨˋ", "ㄈㄚ", "ㄅㄨˋ", "ㄒㄧㄣ", "ㄨㄣˊ"],
        "expected": "衛生福利部發布新聞",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "衛生福利部 is in data.txt",
    },
    {
        "id": "od-name-008",
        "readings": ["ㄐㄧㄠ", "ㄊㄨㄥ", "ㄅㄨˋ", "ㄏㄞˊ", "ㄇㄟˊ", "ㄏㄨㄟˊ", "ㄈㄨˋ"],
        "expected": "交通部還沒回覆",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "交通部 is in data.txt",
    },
    {
        "id": "od-name-009",
        "readings": ["ㄊㄞˊ", "ㄅㄟˇ", "ㄕˋ", "ㄓㄥˋ", "ㄈㄨˇ", "ㄧㄡˇ", "ㄍㄨㄥ", "ㄍㄠˋ"],
        "expected": "臺北市政府有公告",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "present",
        "notes": "臺北市政府 is in data.txt",
    },
    {
        "id": "od-miss-001",
        "readings": ["ㄖㄣˊ", "ㄕˋ", "ㄒㄧㄥˊ", "ㄓㄥˋ", "ㄗㄨㄥˇ", "ㄔㄨˋ", "ㄇㄧㄥˊ", "ㄊㄧㄢ", "ㄎㄞ", "ㄏㄨㄟˋ"],
        "expected": "人事行政總處明天開會",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "missing_candidate",
        "notes": "人事行政總處 is not a whole phrase in data.txt",
    },
    {
        "id": "od-miss-002",
        "readings": ["ㄑㄩˋ", "ㄊㄞˊ", "ㄅㄟˇ", "ㄔㄜ", "ㄓㄢˋ", "ㄆㄥˋ", "ㄇㄧㄢˋ"],
        "expected": "去臺北車站碰面",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "missing_candidate",
        "notes": "臺北車站 is not a whole phrase in data.txt",
    },
    {
        "id": "od-miss-003",
        "readings": ["ㄖㄨㄢˇ", "ㄊㄧˇ", "ㄩㄢˊ", "ㄑㄩ", "ㄈㄨˋ", "ㄐㄧㄣˋ"],
        "expected": "軟體園區附近",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "missing_candidate",
        "notes": "軟體園區 is not a whole phrase in data.txt",
    },
    {
        "id": "od-miss-004",
        "readings": ["ㄌㄜˋ", "ㄕㄢˋ", "ㄌㄧˇ", "ㄌㄧˇ", "ㄓㄤˇ"],
        "expected": "樂善里里長",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "missing_candidate",
        "notes": "樂善里 is not a whole phrase; 樂 reading is hand-annotated as ㄌㄜˋ",
    },
    {
        "id": "od-miss-005",
        "readings": ["ㄒㄧㄣ", "ㄅㄟˇ", "ㄕˋ", "ㄓㄥˋ", "ㄈㄨˇ", "ㄏㄞˊ", "ㄇㄟˊ", "ㄏㄨㄟˊ"],
        "expected": "新北市政府還沒回",
        "protected_english_spans": [],
        "domain": "opendata_name",
        "source": "hand-crafted",
        "license": "MIT",
        "redistributable": True,
        "lexicon_status": "missing_candidate",
        "notes": "新北市政府 is not a whole phrase; 新北市 is present",
    },
]


def main():
    dest = Path(__file__).resolve().parents[2] / (
        "Tests/fixtures/contextual_bopomofo/heldout_opendata_names_2026_08_18.jsonl"
    )
    dest.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in ROWS),
        encoding="utf-8",
    )
    print(f"wrote {len(ROWS)} rows to {dest}")


if __name__ == "__main__":
    main()
